FROM mcr.microsoft.com/powershell:lts-debian-11

# RUN apt-get update \
#     apt-get -y install --no-install-recommends fontconfig \
#     rm -rf /var/lib/apt/lists/*

COPY startup.sh /tmp/startup.sh
COPY library-scripts /tmp/library-scripts